export { About } from "./about";
export { Header } from "./header";
export { Footer } from "./footer";
export { Slider } from "./slider";
export { TopBody } from "./topbody";
export { MainBody } from "./mainbody";
export { Companies } from "./companies";
export { BioGraphi } from "./biographi";
export { ContactForm } from "./contactform";
